### ISSUE TITLE
Project Ideas

### ISSUE THREAD

**Issue by justin-schultz37** [Neuroventure/Fmood-the-Diatry#2]

**Comment by justin-schultz37** [comment]
Online Wholesale Menu for Cannabis Operator

User Story
As Cannabis Operator,
I want to display my Inventory to an Online Menu.
So that my Buyers can see what I have available.

**Comment by Neuroventure** [comment]
Collection of resources for coding-with study guide?

**Comment by justin-schultz37** [comment]
We decided on creating a food journal app that would allow user to log what they eat and rate their mood associated with the meal.
